logging:
  level.root: info
  pattern.console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: guerriers
          binder: local_rabbit
        output:
          destination: guerriers
          binder: local_rabbit
      default.contentType: application/json
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
