version: "3"
services:

  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "myrabbit"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"

  elk:
    image: sebp/elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
